services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: weddingdb
      MYSQL_DATABASE: wishes_db
      MYSQL_USER: zEtzy
      MYSQL_PASSWORD: weddingdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: zEtzy
      DB_PASSWORD: weddingdb
      DB_DATABASE: wishes_db
    depends_on:
      - mysql

volumes:
  mysql_data:

